server:
  port: 8081

spring:
  application:
    name: employee-management
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
    
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false  
      
management:
  security:
    enabled: false  
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always    

springdoc-swagger-ui:
  path: /swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs
